# Generated by Django 5.2.16 on 2026-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon_order_discount_amount_order_user_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='licence_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
