# Generated by Django 5.2.16 on 2026-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_giftcard_alter_category_options_coupon_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_ka',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ka',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='source_item_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('media_type', 'image')), fields=('product',), name='one_primary_image_per_product'),
        ),
    ]
