# Generated by Django 5.2.16 on 2026-07-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_rating_count_and_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_specs',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
