# Generated by Django 5.2.16 on 2026-07-14 08:11

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_duplicate_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited per customer'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='product_uploads/', validators=[store.models.validate_video_upload]),
        ),
    ]
