# Generated by Django 5.2.17 on 2026-08-13 18:27

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_add_coupon_usage_and_media_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), store.models.validate_image_upload]),
        ),
    ]
