services:
  - type: web
    runtime: docker
    name: nexora-django
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /health/ready/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: nexora-django.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://nexora-django.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: nexora-db
          property: connectionString
      - key: DJANGO_CACHE_URL
        fromService:
          type: keyvalue
          name: nexora-cache
          property: connectionString
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: DJANGO_MEDIA_BACKEND
        value: s3
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        value: auto
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_ENABLED
        value: "True"
      - key: GEMINI_MODEL
        value: gemini-2.5-flash-lite

  - type: keyvalue
    name: nexora-cache
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

databases:
  - name: nexora-db
    plan: free
    databaseName: nexora
    user: nexora
