from django.urls import path
from . import views
from . import privacy

urlpatterns = [
    path('product/<str:slug>/rating/', views.rate_product, name='rate_product'),
    path('verify-email/', views.verify_email_view, name='verify_email'),
    path('verify-email/link/<int:user_id>/<str:token>/', views.verify_email_link_view, name='verify_email_link'),
    path('verify-email/resend/', views.resend_verification_view, name='resend_verification'),
    path("", views.home, name="home"),
    path("shop/", views.shop, name="shop"),
    path("product/<str:slug>/", views.product, name="product"),
    path("product/<str:slug>/reviews/", views.product_reviews, name="product_reviews"),
    path("bag/", views.bag, name="bag"),
    path("bag/add/<int:id>/", views.add, name="add"),
    path("bag/update/<int:id>/", views.update, name="update"),
    path("checkout/", views.checkout, name="checkout"),
    path("order/<str:reference>/", views.order_success, name="order_success"),
    path("guide/", views.guide, name="guide"),
    path("login/", views.login_view, name="login"),
    path("password-reset/", views.password_reset_request, name="password_reset"),
    path("password-reset/done/", views.password_reset_code_view, name="password_reset_done"),
    path("password-reset/resend/", views.password_reset_resend_view, name="password_reset_resend"),
    path("password-reset/confirm/", views.password_reset_confirm_view, name="password_reset_confirm"),
    path("password-reset/complete/", views.password_reset_complete_view, name="password_reset_complete"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("cabinet/", views.cabinet_view, name="cabinet"),
    path("cabinet/address/add/", views.add_address_view, name="add_address"),
    path("cabinet/address/delete/<int:id>/", views.delete_address_view, name="delete_address"),
    path("cabinet/data/export/", privacy.account_data_export, name="account_data_export"),
    path("cabinet/delete/request/", privacy.request_account_deletion, name="request_account_deletion"),
    path("cabinet/delete/cancel/", privacy.cancel_account_deletion, name="cancel_account_deletion"),
    path("privacy/", privacy.legal_page, {"document": "privacy"}, name="privacy"),
    path("terms/", privacy.legal_page, {"document": "terms"}, name="terms"),
    path("cookies/", privacy.legal_page, {"document": "cookies"}, name="cookies"),
    path("coupon/apply/", views.apply_coupon_view, name="apply_coupon"),
    path("cart/drawer/", views.cart_drawer_ajax, name="cart_drawer_ajax"),
    path("cart/add/<int:id>/", views.cart_add_ajax, name="cart_add_ajax"),
    path("cart/update/<int:id>/", views.cart_update_ajax, name="cart_update_ajax"),
    path("wishlist/toggle/<int:id>/", views.toggle_wishlist, name="toggle_wishlist"),
    path("compare/", views.compare_view, name="compare"),
    path("compare/toggle/<int:id>/", views.toggle_compare, name="toggle_compare"),
    path("product/<str:slug>/review/", views.add_review, name="add_review"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
]
